name: Publish to PyPI

on:
  push:
    tags:
      - release.*

jobs:
  get_current_branch_name:
    name: Get current branch name
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.get_branch_name.outputs.branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get branch name
        id: get_branch_name
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw##*/}
          echo "branch=$branch" >> $GITHUB_OUTPUT
          echo "Current branch: '$branch'"

  build_and_publish_to_pypi:
    name: Build and publish Python distribution to PyPI
    needs: get_current_branch_name
    if: needs.get_current_branch_name.outputs.branch == 'automatic-publish-to-pypi'
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8.0"

    - name: Build a binary wheel
      run: |
        make build_wheel

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}

  test_installation_from_pypi:
    needs: build_and_publish_to_pypi
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8.0"

    - name: Install and import open-metric-learning package
      run: |
        make pip_install_actual_oml
        python3 -c "from oml.losses.triplet import TripletLoss"
