name: Publish to PyPI

on:
  push:
    tags:
      - release.*

jobs:
  check_tag_status:
    name: Check if the tag is in the main branch commit history
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if the tag is in the main branch commit history
        run: |
          echo $(git branch -a)
          git merge-base --is-ancestor ${{ github.ref }} main

  build_and_publish_to_pypi:
    name: Build and publish Python distribution to PyPI
    needs: check_tag_status
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8.0"

    - name: Build a binary wheel
      run: |
        make build_wheel

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}

  test_installation_from_pypi:
    needs: build_and_publish_to_pypi
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8.0"

    - name: Install and import open-metric-learning package
      run: |
        make pip_install_actual_oml
        python3 -c "from oml.losses.triplet import TripletLoss"
